# Generated by Django 4.2.6 on 2024-05-04 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemorder',
            old_name='Product',
            new_name='product',
        ),
    ]
