# Generated by Django 5.1.1 on 2024-10-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
