# Generated by Django 4.2.6 on 2024-01-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounting',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
