# Generated by Django 4.2.6 on 2024-02-19 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_color_size_product_status_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro', to='home.product'),
        ),
    ]
