# Generated by Django 4.2.6 on 2024-04-04 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_comment_comment_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='image/')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PI', to='home.product')),
            ],
        ),
    ]
